/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package project5;
import javax.swing.JFrame;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;
import static project5.PROJECT5.koneksiDB;
/**
 *
 * @author INFINIX
 */
public class frame1 extends javax.swing.JInternalFrame {
    private boolean isEdit = false;
    private int totalHarga;
    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
        tampil_data();
    }
    
    
    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Kode");
        tabel.addColumn("Barang");
        tabel.addColumn("Harga");
        tabel.addColumn("Nama");
        tabel.addColumn("Jumlah");
        tabel.addColumn("Total Harga");
        tabel.addColumn("Bayar");
        tabel.addColumn("Kembalian");
        
        try{
            java.sql.Connection conn = project5.PROJECT5.koneksiDB();
            String query = "select * from data";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                Object[] row = {rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)
                , rs.getString(7), rs.getString(8)};
                tabel.addRow(row);
            }
            tbldata.setModel(tabel);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbData = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        tfKode = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfBayar = new javax.swing.JTextField();
        cbBarang = new javax.swing.JComboBox<>();
        tfTotal = new javax.swing.JTextField();
        tfKembalian = new javax.swing.JTextField();
        tfJumlah = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        bg2 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Barang", "Harga", "Pembeli", "Jumlah", "Total Harga", "Bayar", "Kembalian"
            }
        ));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldata);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 550, 310));

        btnHapus.setBackground(new java.awt.Color(255, 204, 204));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/aa.png"))); // NOI18N
        jPanel2.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbData.addTab("Informasi Total ", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kode Barang");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel3.setText("Harga Barang");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setText("Total Harga");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel5.setText("Jumlah Pembelian");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel6.setText("Total Pembayaran");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel7.setText("Kembalian");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel8.setText("Pilih Barang");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setText("Nama Pembeli");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btnHitung.setBackground(new java.awt.Color(255, 204, 204));
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel3.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        btnReset.setBackground(new java.awt.Color(255, 204, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel3.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));
        jPanel3.add(tfKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));
        jPanel3.add(tfHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, -1));
        jPanel3.add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, -1));
        jPanel3.add(tfBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 150, -1));

        cbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih Barang", "Cat Air", "Cat Minyak", "Cat Semprot", "Cat Akrilik", " " }));
        cbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBarangActionPerformed(evt);
            }
        });
        jPanel3.add(cbBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 180, -1));
        jPanel3.add(tfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 150, -1));
        jPanel3.add(tfKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 150, -1));
        jPanel3.add(tfJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 180, -1));

        btnSimpan.setBackground(new java.awt.Color(255, 204, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        btnTotal.setBackground(new java.awt.Color(255, 204, 204));
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        jPanel3.add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/aa.png"))); // NOI18N
        jPanel3.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbData.addTab("Aktivitas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbData)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbData)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbldata.getSelectedRow();
        if (selectedRow != -1) {
            String kodeValue = (String) tbldata.getValueAt(selectedRow, 0);
            String barangValue = (String) tbldata.getValueAt(selectedRow, 1);
            String hargaValue = (String) tbldata.getValueAt(selectedRow, 2);
            String namaValue = (String) tbldata.getValueAt(selectedRow, 3);
            String jumlahValue = (String) tbldata.getValueAt(selectedRow, 4);
            String totalValue = (String) tbldata.getValueAt(selectedRow, 5);
            String bayarValue = (String) tbldata.getValueAt(selectedRow, 6);
            String kembalianValue = (String) tbldata.getValueAt(selectedRow, 7);

            tfKode.setText(kodeValue);
            cbBarang.setSelectedItem(barangValue);
            tfHarga.setText(hargaValue);
            tfNama.setText(namaValue);
            tfJumlah.setText(jumlahValue);
            tfTotal.setText(totalValue);
            tfBayar.setText(bayarValue);
            tfKembalian.setText(kembalianValue);

            // Mengaktifkan tombol Edit
            btnSimpan.setText("Edit");
            isEdit = true; // Menandai bahwa ini adalah mode edit
        }
    }//GEN-LAST:event_tbldataMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbldata.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih baris yang ingin dihapus.");
        } else {
            int option = JOptionPane.showConfirmDialog(null,
                "Apakah anda yakin ingin menghapus data tersebut?", "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                try {
                    String kodeToDelete = (String) tbldata.getValueAt(selectedRow, 0);
                    String sql = "DELETE FROM data WHERE Kode = ?";
                    java.sql.Connection conn = (java.sql.Connection)project5.PROJECT5.koneksiDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, kodeToDelete);
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                    tampil_data();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data.");
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(tfHarga.getText());
        int jumlah = Integer.parseInt(tfJumlah.getText());
        // Hitung total harga
        int totalHarga = harga * jumlah;
        // Tampilkan total harga pada komponen tampilan eTotal
        tfTotal.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfKode.setText("");
        cbBarang.setSelectedIndex(0);
        tfHarga.setText("");
        tfNama.setText("");
        tfJumlah.setText("");
        tfTotal.setText("");
        tfBayar.setText("");
        tfKembalian.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void cbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBarangActionPerformed
        // TODO add your handling code here:
        String barang = cbBarang.getSelectedItem().toString();
        int harga = 0;
        switch (barang) {
            case "Cat Air" -> {
                tfKode.setText("007");
                harga = 10000;
            }
            case "Cat Minyak" -> {
                tfKode.setText("010");
                harga = 5000;
            }
            case "Cat Semprot" -> {
                tfKode.setText("003");
                harga = 15000;
            }
            case "Cat Akrilik" -> {
                tfKode.setText("020");
                harga = 20000;
            }
            default -> {
                tfKode.setText("-");
                tfHarga.setText("-");
            }
        }
        tfHarga.setText(String.valueOf(harga));
    }//GEN-LAST:event_cbBarangActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            String kode = tfKode.getText();
            String barang = (String) cbBarang.getSelectedItem();
            String harga = tfHarga.getText();
            String pembeli = tfNama.getText();
            String jumlah = tfJumlah.getText();
            String total = tfTotal.getText();
            String bayar = tfBayar.getText();
            String kembalian = tfKembalian.getText();

            if (kode.equals("Pilihan") || barang.isEmpty() || harga.isEmpty() || pembeli.isEmpty() || jumlah.isEmpty() || total.isEmpty() || bayar.isEmpty() || kembalian.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap isi semua kolom data terlebih dahulu.");
            } else {
                if (isEdit) {
                    int selectedRow = tbldata.getSelectedRow();
                    String pembeliToUpdate = (String) tbldata.getValueAt(selectedRow, 3); // Ganti dengan kolom yang sesuai
                    String sql = "UPDATE data SET Kode = ?, Barang = ?, Harga = ?, Pembeli = ?, Jumlah = ?, TotalHarga = ?, Bayar = ?, Kembalian = ? WHERE Pembeli = ?";
                    java.sql.Connection conn = project5.PROJECT5.koneksiDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, kode);
                    pst.setString(2, barang);
                    pst.setString(3, harga);
                    pst.setString(4, pembeli);
                    pst.setString(5, jumlah);
                    pst.setString(6, total);
                    pst.setString(7, bayar);
                    pst.setString(8, kembalian);
                    pst.setString(9, pembeliToUpdate);
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Data berhasil diupdate.");
                    isEdit = false;
                    btnSimpan.setText("Simpan");
                } else {
                    // Mode Simpan: Simpan data baru
                    String sql = "INSERT INTO data (Kode, Barang, Harga, Pembeli, Jumlah, TotalHarga, Bayar, Kembalian) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                    java.sql.Connection conn = project5.PROJECT5.koneksiDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, kode);
                    pst.setString(2, barang);
                    pst.setString(3, harga);
                    pst.setString(4, pembeli);
                    pst.setString(5, jumlah);
                    pst.setString(6, total);
                    pst.setString(7, bayar);
                    pst.setString(8, kembalian);
                    pst.executeUpdate();
                    tbData.setSelectedIndex(1);
                    JOptionPane.showMessageDialog(null, "Berhasil disimpan");
                }
//                reset();
                tampil_data();
            }

            tampil_data();
            tbData.setSelectedIndex(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        int bayar = Integer.parseInt(tfBayar.getText());
        // Ambil total harga dari komponen tampilan
        int totalHarga = Integer.parseInt(tfTotal.getText());
        // Hitung kembalian
        int kembalian = bayar - totalHarga;
        // Tampilkan kembalian pada komponen tampilan eKembalian
        tfKembalian.setText("Rp " + kembalian);
    }//GEN-LAST:event_btnTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg2;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tbData;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextField tfBayar;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfKembalian;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
